const sidebarSettings = {
  docs: [
    "docs/introduction",
    "docs/supported-data-platforms",
    "docs/installation",
    "docs/deploy",
    {
      type: "category",
      label: "Tutorials",
      items: [
        "reference/commands/serve",
        "reference/commands/generate-crud",
        "reference/commands/streamlit",
      ]
    },
    {
      type: "category",
      label: "Frequently asked questions",
      link: {
        type: "generated-index",
        title: "Frequently asked questions",
        description:
          "Our Frequently Asked Questions (FAQs) section is a space where you can find an answer to some questions we get asked a lot (but that we’re happy to answer!). If you have a question or are still stuck on something, please create a discussion on Github.",
        slug: "/docs/faqs",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "faqs",
        },
      ],
    },
    "docs/architecture",
  ],
  reference: [
    {
      type: "category",
      label: "Project configs",
      items: [
        "reference/jinjat_project.yml",
      ]
    },
    {
      type: "category",
      label: "For models",
      items: [
        "reference/model-properties"
      ],
    },
    {
      type: "category",
      label: "For analyses",
      items: ["reference/analysis-properties"],
    },
    {
      type: "category",
      label: "For exposures",
      items: ["reference/exposure-properties"],
    },
    {
      type: "category",
      label: "List of commands",
      items: [
        "reference/commands/serve",
        "reference/commands/generate-crud",
        "reference/commands/streamlit",
      ]
    }
  ]
};

module.exports = sidebarSettings;
