const sidebarSettings = {
  docs: [
    "docs/introduction",
    "docs/supported-data-platforms",
    "docs/installation",
    "docs/getting-started",
    "docs/api-routes",
    "docs/authorization",
    {
      type: "category",
      label: "Integrations",
      link: {
        type: "generated-index",
        title: "Integrations",
        slug: "/docs/integration",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "integrations",
        },
      ],
    },
    "docs/deploy",
    "docs/advanced",
    {
      type: "category",
      label: "Frequently asked questions",
      link: {
        type: "generated-index",
        title: "Frequently asked questions",
        description:
          "Our Frequently Asked Questions (FAQs) section is a space where you can find an answer to some questions we get asked a lot (but that we’re happy to answer!). If you have a question or are still stuck on something, please create a discussion on Github.",
        slug: "/docs/faqs",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "faqs",
        },
      ],
    },
  ],
  reference: [
    {
      type: "category",
      label: "Project configs",
      items: [
        "reference/jinjat_project.yml",
      ]
    },
    {
      type: "category",
      label: "Resource configs",
      items: [
        "reference/model-properties",
        "reference/analysis-properties",
        "reference/exposure-properties",
      ],
    },
    {
      type: "category",
      label: "List of commands",
      items: [
        "reference/commands/serve",
        "reference/commands/generate",
        "reference/commands/streamlit",
      ]
    }
  ]
};

module.exports = sidebarSettings;
